random_seed: 444

dataset:
  type: &dataset_type 'KITTI'
  root_dir: 'path'
  train_split: 'train'
  test_split: 'val'
  batch_size: 1
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: 'anno'
  meanshape: False  
  writelist: ['Car']
  clip_2d: False

  aug_pd: True
  aug_crop: True

  random_flip: 0.5
  random_crop: 0.5
  random_mixup3d: 0.5
  scale: 0.05
  shift: 0.05

  range_scale: 'normal'


model_name: 'monoem'
model:
  num_classes: 3
  return_intermediate_dec: True
  device: 'cuda'

  # Backbone
  backbone: 'resnet50'
  train_backbone: True
  num_feature_levels: 4
  dilation: False
  position_embedding: 'sine' 

  # range predictor
  mode: LID
  num_range_bins: 80
  range_min: 1e-3
  range_max: 60.0

  # Transformer
  with_box_refine: True
  use_dn: False
  init_box: False
  enc_layers: 3
  dec_layers: 3
  hidden_dim: 256
  dim_feedforward: 256
  dropout: 0.1
  nheads: 8
  num_queries: 50
  group_num: 11
  enc_n_points: 4
  dec_n_points: 4
  # DN
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0
  # Loss
  aux_loss: True

  # Loss coefficients
  cls_loss_coef: 2
  focal_alpha: 0.25

  bbox_loss_coef: 5
  giou_loss_coef: 2
  3dcenter_loss_coef: 10
  dim_loss_coef: 1
  angle_loss_coef: 1
  range_loss_coef: 1
  range_map_loss_coef: 1
  region_loss_coef: 1

  # cycle loss
  cycle_loss_coef: 0

  # Matcher
  set_cost_class: 2
  set_cost_bbox: 5
  set_cost_giou: 2
  set_cost_3dcenter: 10


optimizer:
  type: 'adamw'
  lr: 0.0002
  weight_decay: 0.0001


lr_scheduler:
  type: 'step'  
  warmup: False  
  decay_rate: 0.5
  decay_list: [85, 125, 165, 205]


trainer:
  max_epoch: 250
  gpu_ids: '1'
  save_frequency: 1  
  # resume_model: True
  pretrain_model: pretrain
  save_path: 'outputs/'
  save_all: False  
  use_dn: False
  scalar: 5
  label_noise_scale: 0.2
  box_noise_scale: 0.4
  num_patterns: 0

tester:
  type: *dataset_type
  mode: single  
  checkpoint: 195 
  threshold: 0.2  
  topk: 50
